name: 'olympic_medals'
version: '1.0.0'
config-version: 2

profile: 'olympic_medals'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  olympic_medals:
    staging:
      +materialized: view
      +schema: PUBLIC
    marts:
      +materialized: table
      +schema: PUBLIC